# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  registrationserviceapi:
    container_name: registrationserviceapi
    image: registrationserviceapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SIGNATURE_SERVICE: http://licensesignatureservice
    ports:
      - 5001:5001

  licensesignatureservice:
    container_name: licensesignatureservice
    image: licensesignatureservice
    build:
      context: ./LicenseSignatureService
      dockerfile: Dockerfile
    ports:
      - 5002:5002